// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIX6k7lMhRB0mK8Wk6DVVV9Y7GdAw2CoQ',
    appId: '1:506442014928:android:66322cf1f19f9fd00bbed5',
    messagingSenderId: '506442014928',
    projectId: 'cosmic-life-coach-f8dd5',
    storageBucket: 'cosmic-life-coach-f8dd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXiPryZ45Fki1YhMMbt5tC2Yghq8QA3xI',
    appId: '1:506442014928:ios:fb9b565d4de26b040bbed5',
    messagingSenderId: '506442014928',
    projectId: 'cosmic-life-coach-f8dd5',
    storageBucket: 'cosmic-life-coach-f8dd5.firebasestorage.app',
    iosClientId: '506442014928-jn2l734r08s6qdntpir6qqosidbnnv1d.apps.googleusercontent.com',
    iosBundleId: 'com.vinay.cosmicCoach',
  );
}
