/// Where the story begins. Firebase wakes up, Riverpod's ProviderScope
/// wraps the world, and Cosmic Coach takes the stage.
///
/// NOTE: `firebase_options.dart` is generated by `flutterfire configure`
/// (run it once after registering the app in the Firebase console) —
/// uncomment the import and options argument afterwards.
library;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import 'app.dart';
import 'core/logging/app_logger.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform, // after flutterfire configure
  );
  appLogger.i('Firebase initialized — launching Cosmic Coach');

  runApp(const ProviderScope(child: CosmicCoachApp()));
}
